AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-base

  Example SAM Template for aws-base projects
  
Parameters:

  StackName:
    Type: String
  AppPrefix:
    Type: String
  # ApiVersion:
  #   Type: String
  EnableSQS:
    Type: String
    AllowedValues: [true, false]
    Default: true
  SourceBucket:
    Type: String
    Default: agb-app-source
  ApiStageName:
    Type: String
    Default: dev

Globals:

  Function:
    Runtime: nodejs12.x
    Timeout: 3
    CodeUri:
      Bucket: !Sub ${SourceBucket}
      Key: !Sub ${StackName}/lambda.zip
  
Resources:

  DocumentUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${AppPrefix}-document-update-topic

  DocumentUpdateTopicPolicy:
    # This policy is required to allow S3 to publish to the topic, otherwise we get circular dependencies
    Type: AWS::SNS::TopicPolicy
    Properties: 
      Topics: 
        - !Ref DocumentUpdateTopic
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - SNS:Publish
            Effect: Allow
            Resource: !Ref DocumentUpdateTopic
            Principal:  
              Service: s3.amazonaws.com

  DocumentBucket:
    Type: AWS::S3::Bucket
    DependsOn: DocumentUpdateTopic
    Properties: 
      BucketName: !Sub ${AppPrefix}-document-bucket
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            Topic: !Ref DocumentUpdateTopic

  DocumentIndexTable:    
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub ${AppPrefix}-document-index-table
      BillingMode: PAY_PER_REQUEST
      # ProvisionedThroughput: 
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions: 
        - 
          AttributeName: documentType
          AttributeType: S
        - 
          AttributeName: documentId
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: documentType
          KeyType: HASH
        - 
          AttributeName: documentId
          KeyType: RANGE

  DocumentIndexerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-document-indexer-function
      Handler: index.handleDocumentUpdate
      Environment:
        Variables:
          # UNPROCESSED_UPDATE_QUEUE_URL: !Ref UnprocessedFileUpdateQueue
          DOCUMENT_INDEX_TABLE_NAME: !Ref DocumentIndexTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentIndexTable
        # - SQSSendMessagePolicy:
        #     QueueName: !GetAtt UnprocessedFileUpdateQueue.QueueName
      Events:
        FileUpdateEvent:
          Type: SNS
          Properties:
            Topic: !Ref DocumentUpdateTopic

  DocumentUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${AppPrefix}-document-update-topic

  DocumentUpdatePublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-document-update-publisher-function
      Handler: index.handleDocumentIndexStream
      Environment:
        Variables:
          DOCUMENT_UPDATE_TOPIC: !Ref DocumentUpdateTopic
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName: !Ref DocumentIndexTable
            StreamName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DocumentUpdateTopic.TopicName
      Events:
        DatabaseEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DocumentIndexTable.StreamArn
            Enabled: !Ref EnableSQS
            MaximumRetryAttempts: 0
            StartingPosition: TRIM_HORIZON

  AffordabilityApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
      Name: !Sub ${AppPrefix}-AffordabilityApi
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: PER_API
          # Quota:
          #   Limit: 500
          #   Period: MONTH
          # Throttle:
          #   BurstLimit: 100
          #   RateLimit: 50

  AffordabilityApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${AppPrefix}-affordability-api-function
      Handler: index.handleAffordabilityApiRequest
      Environment:
        Variables:
          FILE_BUCKET: !Ref DocumentBucket
          DOCUMENT_INDEX_TABLE_NAME: !Ref DocumentIndexTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentIndexTable
      Events:
        HttpEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /affordability

  UpdateConfigurationApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-update-configuration-api-function
      Handler: index.handleUpdateConfigurationApiRequest
      Environment:
        Variables:
          FILE_BUCKET: !Ref DocumentBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DocumentBucket
      Events:
        HttpEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /document/configuration/{configurationType}

  UpdateScenarioApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-update-scenario-api-function
      Handler: index.handleUpdateScenarioApiRequest
      Environment:
        Variables:
          FILE_BUCKET: !Ref DocumentBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DocumentBucket
      Events:
        HttpEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /scenario

Outputs:

  AffordabilityApi:
    Description: "Affordability API URL"
    Value: !Sub "https://${AffordabilityApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/affordability"

  AffordabilityApiFunctionARN:
    Description: "Affordability API Function ARN"
    Value: !GetAtt AffordabilityApiFunction.Arn
    

