AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-base

  Example SAM Template for aws-base projects
  
Parameters:

  StackName:
    Type: String
  AppPrefix:
    Type: String
  AssetVersion:
    Type: String
  EnableSQS:
    Type: String
    AllowedValues: [true, false]
    Default: true
  SourceBucket:
    Type: String
    Default: agb-app-source
  ApiStageName:
    Type: String
    Default: dev

Globals:

  Function:
    Runtime: nodejs12.x
    Timeout: 3
    CodeUri:
      Bucket: !Sub ${SourceBucket}
      Key: !Sub ${StackName}/lambda.zip
  
Resources:

  DocumentUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${AppPrefix}-document-update-topic

  DocumentUpdateTopicPolicy:
    # This policy is required to allow S3 to publish to the topic, otherwise we get circular dependencies
    Type: AWS::SNS::TopicPolicy
    Properties: 
      Topics: 
        - !Ref DocumentUpdateTopic
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - SNS:Publish
            Effect: Allow
            Resource: !Ref DocumentUpdateTopic
            Principal:  
              Service: s3.amazonaws.com

  DocumentBucket:
    Type: AWS::S3::Bucket
    DependsOn: DocumentUpdateTopic
    Properties: 
      BucketName: !Sub ${AppPrefix}-document-bucket
      NotificationConfiguration:
        TopicConfigurations:
          - Event: 's3:ObjectCreated:*'
            Topic: !Ref DocumentUpdateTopic

  DocumentIndexTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Sub ${AppPrefix}-document-index-table
      BillingMode: PAY_PER_REQUEST
      # ProvisionedThroughput: 
      #   ReadCapacityUnits: 5
      #   WriteCapacityUnits: 5
      StreamSpecification: 
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions: 
        - 
          AttributeName: documentType
          AttributeType: S
        - 
          AttributeName: documentId
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: documentType
          KeyType: HASH
        - 
          AttributeName: documentId
          KeyType: RANGE

  DocumentIndexerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-document-indexer-function
      Handler: index.handleDocumentIndexerFunction
      Environment:
        Variables:
          # UNPROCESSED_UPDATE_QUEUE_URL: !Ref UnprocessedFileUpdateQueue
          DOCUMENT_INDEX_TABLE_NAME: !Ref DocumentIndexTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentIndexTable
      Events:
        FileUpdateEvent:
          Type: SNS
          Properties:
            Topic: !Ref DocumentUpdateTopic

  DocumentIndexUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${AppPrefix}-document-index-update-topic

  DocumentIndexUpdatePublisherFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-document-index-update-publisher-function
      Handler: index.handleDocumentIndexUpdatePublisherFunction
      Environment:
        Variables:
          DOCUMENT_UPDATE_TOPIC: !Ref DocumentIndexUpdateTopic
      Policies:
        - DynamoDBStreamReadPolicy:
            TableName: !Ref DocumentIndexTable
            StreamName: "*"
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt DocumentIndexUpdateTopic.TopicName
      Events:
        DatabaseEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DocumentIndexTable.StreamArn
            Enabled: !Ref EnableSQS
            MaximumRetryAttempts: 0
            StartingPosition: TRIM_HORIZON

  RecalculationInitiatorSubscription:
    Type: AWS::SNS::Subscription
    Properties: 
      Endpoint: !GetAtt RecalculationInitiatorQueue.Arn
      FilterPolicy: 
        documentType: [ configuration, scenario, product ]
      Protocol: sqs
      TopicArn: !Ref DocumentIndexUpdateTopic

  RecalculationInitiatorQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AppPrefix}-recalculation-initiator-queue
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RecalculationInitiatorDLQ.Arn
        maxReceiveCount: 1

  RecalculationInitiatorDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AppPrefix}-recalculation-initiator-dlq
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 18

  RecalculationInitiatorQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref RecalculationInitiatorQueue
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - SQS:SendMessage
            Effect: Allow
            Resource: !GetAtt RecalculationInitiatorQueue.Arn
            Principal:  
              Service: sns.amazonaws.com # TODO: Could this be more restrictive?

  RecalculationInitiatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-recalculation-initiator-function
      Handler: index.handleRecalculationInitiatorFunction
      Environment:
        Variables:
          RECALCULATION_STATE_MACHINE_ARN: !Ref RecalculationStateMachine
          DOCUMENT_INDEX_TABLE_NAME: !Ref DocumentIndexTable
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt RecalculationInitiatorQueue.QueueName
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentIndexTable
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt RecalculationStateMachine.Name
      Events:
        UnprocessedUpdateEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RecalculationInitiatorQueue.Arn
            BatchSize: 10
            Enabled: !Ref EnableSQS

  RecalculationStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub ${AppPrefix}-recalculation-state-machine
      # TODO: For express state machines we need to add logging: https://www.davehall.com.au/blog/dave/2020/07/10/logging-step-functions-cloudwatch
      # Type: EXPRESS
      Type: STANDARD
      DefinitionUri:
        Bucket: !Sub ${SourceBucket}
        Key: !Sub ${StackName}/statemachine-${AssetVersion}/recalculation.asl.json
      Policies:
        - AWSLambdaRole

  AffordabilityApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
      Name: !Sub ${AppPrefix}-AffordabilityApi
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: PER_API
          # Quota:
          #   Limit: 500
          #   Period: MONTH
          # Throttle:
          #   BurstLimit: 100
          #   RateLimit: 50

  AffordabilityApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-affordability-api-function
      Handler: index.handleAffordabilityApiFunction
      Environment:
        Variables:
          DOCUMENT_BUCKET: !Ref DocumentBucket
          DOCUMENT_INDEX_TABLE_NAME: !Ref DocumentIndexTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - DynamoDBReadPolicy:
            TableName: !Ref DocumentIndexTable
      Events:
        HttpEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /affordability

  DocumentApiUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-document-api-update-function
      Handler: index.handleDocumentApiUpdateFunction
      Environment:
        Variables:
          DOCUMENT_BUCKET: !Ref DocumentBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DocumentBucket
      Events:
        InsertEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /document/{type}
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /document/{type}/{id}

Outputs:

  AffordabilityApi:
    Description: "Affordability API URL"
    Value: !Sub "https://${AffordabilityApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/affordability"

  AffordabilityApiFunctionARN:
    Description: "Affordability API Function ARN"
    Value: !GetAtt AffordabilityApiFunction.Arn
    

