AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-base

  Example SAM Template for aws-base projects
  
Parameters:

  StackName:
    Type: String
  AppPrefix:
    Type: String
  # ApiVersion:
  #   Type: String
  EnableSQS:
    Type: String
    AllowedValues: [true, false]
    Default: true
  SourceBucket:
    Type: String
    Default: agb-app-source
  ApiStageName:
    Type: String
    Default: dev

Globals:

  Function:
    Runtime: nodejs12.x
    Timeout: 3
    CodeUri:
      Bucket: !Sub ${SourceBucket}
      Key: !Sub ${StackName}/lambda.zip
  
Resources:

  FileUpdateEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AppPrefix}-file-update-event-queue
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 18
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FileUpdateEventDLQ.Arn
        maxReceiveCount: 1

  FileUpdateEventDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AppPrefix}-file-update-event-dlq
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 18

  FileUpdateEventQueuePolicy: # Required to allow S3 to send to the queue, otherwise we get circular dependencies
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref FileUpdateEventQueue
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - SQS:SendMessage
            Effect: Allow
            Resource: !GetAtt FileUpdateEventQueue.Arn
            Principal:  
              Service: s3.amazonaws.com

  FileBucket:
    Type: AWS::S3::Bucket
    DependsOn: FileUpdateEventQueue
    Properties: 
      BucketName: !Sub ${AppPrefix}-file-bucket
      NotificationConfiguration:
        QueueConfigurations:
        - Event: 's3:ObjectCreated:*'
          Queue: !GetAtt FileUpdateEventQueue.Arn

  FileUpdateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AppPrefix}-file-update-event-function
      Handler: index.handleFileUpdateEvent
      # Environment:
      #   Variables:
      #     UNPROCESSED_UPDATE_QUEUE_URL: !Ref UnprocessedFileUpdateQueue
      # Policies:
      #   - SQSSendMessagePolicy:
      #       QueueName: !GetAtt UnprocessedFileUpdateQueue.QueueName
      #   - S3ReadPolicy:
      #       BucketName: !Ref FileBucket
      Events:
        FileUpdateEventQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt FileUpdateEventQueue.Arn
            BatchSize: 10
            Enabled: !Ref EnableSQS

  AffordabilityApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
      Name: !Sub ${AppPrefix}-AffordabilityApi
      EndpointConfiguration: REGIONAL
      Auth:
        ApiKeyRequired: true # sets for all methods
        UsagePlan:
          CreateUsagePlan: PER_API
          # Quota:
          #   Limit: 500
          #   Period: MONTH
          # Throttle:
          #   BurstLimit: 100
          #   RateLimit: 50

  AffordabilityApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${AppPrefix}-affordability-api-function
      Handler: index.handleAffordabilityApiRequest
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
          FILE_BUCKET: !Ref FileBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref FileBucket
      Events:
        HttpEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /affordability

  UpdateConfigurationApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${AppPrefix}-update-configuration-api-function
      Handler: index.handleUpdateConfigurationApiRequest
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
          FILE_BUCKET: !Ref FileBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FileBucket
      Events:
        HttpEvent:
          Type: Api
          Properties:
            RestApiId: !Ref AffordabilityApi
            Method: POST
            Path: /configuration

Outputs:

  AffordabilityApi:
    Description: "Affordability API URL"
    Value: !Sub "https://${AffordabilityApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/affordability"

  AffordabilityApiFunctionARN:
    Description: "Affordability API Function ARN"
    Value: !GetAtt AffordabilityApiFunction.Arn
    

