AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-base

  Example SAM Template for aws-base projects
  
Parameters:
  StackName:
    Type: String
  AppPrefix:
    Type: String
  # ApiVersion:
  #   Type: String
  EnableSQS:
    Type: String
    AllowedValues: [true, false]
    Default: true
  SourceBucket:
    Type: String
    Default: agb-app-source

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 3
    CodeUri:
      Bucket: !Sub ${SourceBucket}
      Key: !Sub ${StackName}/lambda.zip
  
Resources:
  BasicFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub ${AppPrefix}-BasicFunction
      Handler: index.handleBasicFunction
      # Environment:
      #   Variables:
      # Policies:
      # Events:

Outputs:
  BasicFunctionARN:
    Description: "Basic Lambda Function ARN"
    Value: !GetAtt BasicFunction.Arn
